# =============================================================================
# H5 App - 缓存配置
# =============================================================================

type: ${HAI_CACHE_TYPE:memory}
