# =============================================================================
# Corporate Website - 数据库配置
# =============================================================================

type: ${HAI_RELDB_TYPE:sqlite}
database: ${HAI_RELDB_DATABASE:./data/corporate-website.db}
