# =============================================================================
# API Service - 缓存配置
# =============================================================================

type: ${HAI_CACHE_TYPE:memory}
